name: Upload to Maven Central Repository

on: workflow_dispatch

jobs:
  update_version:
    runs-on: ubuntu-20.04
    steps:
      - name: Get latest version and update based on last commit
        run: ./bump_version.sh
  publish:
    needs: update_version
    runs-on: ubuntu-20.04
    steps:
      - name: Install GPG secret key
        run: echo "${{ secrets.OSSRH_GPG_SECRET_KEY }}" | gpg --batch --import
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Java with Maven
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
      - name: Publish to Maven Central
        run: |
          mvn \
            --no-transfer-progress \
            --batch-mode \
            -Dgpg.passphrase=${{ secrets.OSSRH_GPG_SECRET_KEY_PASSWORD }} \
            clean deploy
        working-directory: 'string-array-utils'
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_PASSWORD }}